---
- name: "(Install: All OSs) Install NGINX Perl Module"
  package:
    name: nginx-module-perl
    state: present
  when: type == "opensource"

- name: "(Install: All OSs) Install NGINX Perl Module"
  package:
    name: nginx-plus-module-perl
    state: present
  when: type == "plus"

- name: "(Setup: All NGINX) Load NGINX Perl Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_http_perl.so;
  notify: "(Handler: All OSs) Reload NGINX"
