---
- name: "(Install: All OSs) Install NGINX Open Source JavaScript Module"
  package:
    name: "nginx-module-njs{{ nginx_version | default('') }}"
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus JavaScript Module"
  package:
    name: "nginx-plus-module-njs{{ nginx_version | default('') }}"
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX JavaScript Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: "{{ item }}"
  with_items:
    - load_module modules/ngx_http_js_module.so;
    - load_module modules/ngx_stream_js_module.so;
  when: not nginx_main_template_enable
  notify: "(Handler: All OSs) Reload NGINX"
