---
- name: "(Install: All OSs) Install NGINX Open Source GeoIP Module"
  package:
    name: nginx-module-geoip
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus GeoIP Module"
  package:
    name: nginx-plus-module-geoip
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX GeoIP Module"
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    block: |
      load_module modules/ngx_http_geoip_module.so;
      load_module modules/ngx_stream_geoip_module.so;
  notify: "(Handler: All OSs) Reload NGINX"
