---
- name: "(Install: All OSs) Install NGINX Open Source XSLT Module"
  package:
    name: nginx-module-xslt
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus XSLT Module"
  package:
    name: nginx-plus-module-xslt
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX XSLT Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_http_xslt_filter_module.so;
  notify: "(Handler: All OSs) Reload NGINX"
