---
- name: "(Install: All OSs) Install NGINX Open Source Image Filter Module"
  package:
    name: "nginx-module-image-filter{{ nginx_version | default('') }}"
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus Image Filter Module"
  package:
    name: "nginx-plus-module-image-filter{{ nginx_version | default('') }}"
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX Image Filter Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_http_image_filter_module.so;
  when: not nginx_main_template_enable
  notify: "(Handler: All OSs) Reload NGINX"
