---
- name: "(Install: All OSs) Install Perl Dependency"
  package:
    name: perl
    state: present

- name: "(Install: All OSs) Install NGINX Open Source Perl Module"
  package:
    name: "nginx-module-perl{{ nginx_version | default('') }}"
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus Perl Module"
  package:
    name: "nginx-plus-module-perl{{ nginx_version | default('') }}"
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX Perl Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_http_perl_module.so;
  when: not nginx_main_template_enable
  notify: "(Handler: All OSs) Reload NGINX"
