---
sudo: required
language: python
services:
  - docker
env:
  - scenario: default
  - scenario: stable_push
  - scenario: template_module
  - scenario: unit
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule[docker]
script:
  - travis_wait 40 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
