---
language: python
services: docker
jobs:
  include:
    - name: "(Debian/Ubuntu) Install Specific Version"
      env:
        scenario: default
    - name: "(Alpine Linux) Install Specific Version"
      env:
        scenario: default_alpine
    - name: "(CentOS) Install Specific Version"
      env:
        scenario: default_centos
    - name: "(Debian/Ubuntu) Install Modules"
      env:
        scenario: module
    - name: "(Alpine Linux) Install Modules"
      env:
        scenario: module_alpine
    - name: "(CentOS) Install Modules"
      env:
        scenario: module_centos
    - name: "(Debian/Ubuntu) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push
    - name: "(Alpine Linux) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push_alpine
    - name: "(CentOS) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push_centos
    - name: "(Debian/Ubuntu) Use Template Setting"
      env:
        scenario: template
    - name: "(Alpine Linux) Use Template Setting"
      env:
        scenario: template_alpine
    - name: "(CentOS) Use Template Setting"
      env:
        scenario: template_centos
    - name: "(Debian/Ubuntu) Install NGINX Unit"
      env:
        scenario: unit
    - name: "(Alpine Linux) Install NGINX Unit"
      env:
        scenario: unit_alpine
    - name: "(CentOS) Install NGINX Unit"
      env:
        scenario: unit_centos
    - name: "(Debian/Ubuntu) Install from Source"
      env:
        scenario: source
    - name: "(Alpine Linux) Install from Source"
      env:
        scenario: source_alpine
    - name: "(CentOS) Install from Source"
      env:
        scenario: source_centos
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - pip install ansible==2.9.13
  - pip install ansible-lint==4.3.4
  - pip install yamllint==1.24.2
  - pip install molecule==3.0.8
  - pip install docker==4.3.1
script:
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
