---
- import_tasks: prerequisites/install-prerequisites.yml

- import_tasks: keys/apt-key.yml
  when:
    - ansible_os_family == "Debian"
    - nginx_install_from == "nginx_repository"
      or nginx_amplify_enable
      or nginx_controller_enable
      or nginx_unit_enable

- import_tasks: keys/rpm-key.yml
  when:
    - ansible_os_family == "RedHat"
      or ansible_os_family == "Suse"
    - nginx_install_from == "nginx_repository"
      or nginx_amplify_enable
      or nginx_controller_enable
      or nginx_unit_enable

- name: "(Install: Debian/Ubuntu/CentOS/RedHat/FreeBSD) Install NGINX"
  block:

    - import_tasks: opensource/install-oss.yml
      when: nginx_type == "opensource"

    - import_tasks: plus/install-plus.yml
      when: nginx_type == "plus"

    - import_tasks: modules/install-modules.yml
      when: true in nginx_modules.values()

    - import_tasks: conf/upload-config.yml
      when: nginx_main_upload_enable
            or nginx_http_upload_enable
            or nginx_stream_upload_enable
            or nginx_html_upload_enable
            or nginx_ssl_upload_enable

    - import_tasks: conf/template-config.yml
      when: nginx_main_template_enable
            or nginx_http_template_enable
            or nginx_stream_template_enable

    - import_tasks: conf/setup-status.yml
      when: nginx_status_enable

    - import_tasks: conf/setup-rest-api.yml
      when: nginx_rest_api_enable

    - import_tasks: conf/debug-output.yml
      when: nginx_debug_output

  when: nginx_enable

- import_tasks: amplify/install-amplify.yml
  when:
    - nginx_amplify_enable
    - nginx_amplify_api_key is defined
    - nginx_amplify_api_key

- import_tasks: controller/install-controller.yml
  when:
    - nginx_controller_enable
    - nginx_controller_api_key is defined
    - nginx_controller_api_key
    - nginx_controller_api_endpoint is defined
    - nginx_controller_api_endpoint

- import_tasks: unit/install-unit.yml
  when: nginx_unit_enable
