---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      package:
        name: nginx
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Check default.conf does not exist
      stat:
        path: /etc/nginx/conf.d/default.conf
      check_mode: true
      register: stat_result
      failed_when: stat_result.stat.exists
