---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Set module if Alpine
      set_fact:
        module:
          - unit-perl
          - unit-php7
          - unit-python3
      when: ansible_facts['os_family'] == "Alpine"
    - name: Set module if Debian
      set_fact:
        module:
          - unit-perl
          - unit-php
          - unit-ruby
      when: ansible_facts['os_family'] == "Debian"
    - name: Set module if Red Hat
      set_fact:
        module:
          - unit-php
          - unit-go
      when: ansible_facts['os_family'] == "RedHat"
  tasks:
    - name: Install NGINX Unit
      include_role:
        name: ansible-role-nginx
      vars:
        nginx_enable: false
        nginx_unit_enable: true
        nginx_unit_modules: "{{ module }}"
