---
- name: (Debian/Ubuntu) Add NGINX Amplify agent repository
  ansible.builtin.apt_repository:
    filename: nginx-amplify
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://packages.amplify.nginx.com/py3/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['distribution_release'] | lower }} amplify-agent
    update_cache: true
    mode: 0644
