---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 9.2.0
  - name: community.crypto
    version: 2.21.1
  - name: community.docker
    version: 3.11.0
