---
collections:
  - name: ansible.posix
    version: 1.5.2
  - name: community.general
    version: 6.6.0
  - name: community.crypto # Only required if you plan to install NGINX Plus
    version: 2.13.0
  - name: community.docker # Only required if you plan to use Molecule
    version: 3.4.5
