---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.5.0
  - name: community.crypto
    version: 2.26.0
  - name: community.docker
    version: 4.5.2
