---
- name: "(Handler: All OSs) Run NGINX"
  block:

    - name: "(Handler: All OSs) Start NGINX"
      service:
        name: nginx
        state: started
        enabled: yes

    - name: "(Handler: All OSs) Reload NGINX"
      service:
        name: nginx
        state: reloaded

  when:
    - nginx_start | bool
    - not ansible_check_mode

- name: "(Handler: All OSs) Start NGINX Amplify Agent"
  service:
    name: amplify-agent
    state: started

- name: "(Handler: Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit"
  service:
    name: unit
    state: started
    enabled: yes

- name: "(Handler: FreeBSD) Start NGINX Unit"
  service:
    name: unitd
    state: started
    enabled: yes

- name: "(Handler: CentOS/RedHat) Enable NGINX"
  systemd:
    name: nginx
    state: started
    #daemon_reload: yes
    enabled: yes

- name: "(Handler: All OSs) Enable NGINX"
  service:
    name: nginx
    state: started
    enabled: yes
