---
- name: "(Handler: All OSs) Start NGINX"
  service:
    name: nginx
    state: started
    enabled: yes

- name: "(Handler: All OSs) Reload NGINX"
  service:
    name: nginx
    state: reloaded

- name: "(Handler: All OSs) Start NGINX Amplify Agent"
  service:
    name: amplify-agent
    state: started

- name: "(Handler: All OSs) Start NGINX Controller Agent"
  service:
    name: controller-agent
    state: started

- name: "(Handler: Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit"
  service:
    name: unit
    state: started
    enabled: yes

- name: "(Handler: FreeBSD) Start NGINX Unit"
  service:
    name: unitd
    state: started
    enabled: yes
