---
# handlers file for ansible-role-nginx
- name: "(Handler: All OSs) Enable SELinux"
  include_tasks: "{{ role_path }}/tasks/prerequisites/setup-selinux.yml"

- name: "(Handler: All OSs) Check NGINX"
  command: "nginx -t"
  changed_when: false

- name: "(Handler: All OSs) Run NGINX"
  block:

    - name: "(Handler: All OSs) Reload NGINX"
      command: "nginx -s reload"
      changed_when: false

    - name: "(Handler: All OSs) Start NGINX"
      service:
        name: nginx
        state: started
        enabled: yes
      notify: "(Handler: All OSs) Check NGINX"

  when:
    - nginx_start | bool
    - not ansible_check_mode

- name: "(Handler: All OSs) Start NGINX Amplify Agent"
  service:
    name: amplify-agent
    state: started

- name: "(Handler: Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit"
  service:
    name: unit
    state: started
    enabled: yes

- name: "(Handler: FreeBSD) Start NGINX Unit"
  service:
    name: unitd
    state: started
    enabled: yes
