---
- name: "(Setup: Linux) Create Override Directory For NGINX Systemd Service"
  file:
    path: "{{ nginx_service_overridepath }}"
    state: directory
    mode: 0755

- name: "(Setup: Linux) Create Override For NGINX Systemd Service"
  template:
    src: "{{ role_path }}/templates/services/nginx.service.override.conf.j2"
    dest: "{{ nginx_service_overridepath }}/{{ nginx_service_overridefilename }}"
    owner: root
    group: root
    mode: 0644
  notify: "(Handler: All OSs) Systemd Daemon-Reload"
  when:
    - not nginx_service_custom | bool
    - not nginx_service_clean | bool

- name: "(Setup: Linux) Customize Override For NGINX Systemd Service"
  copy:
    src: "{{ nginx_service_custom_file }}"
    dest: "{{ nginx_service_overridepath }}/{{ nginx_service_overridefilename }}"
    owner: root
    group: root
    mode: 0644
  notify: "(Handler: All OSs) Systemd Daemon-Reload"
  when:
    - nginx_service_custom | bool
    - not nginx_service_clean | bool

- name: "(Setup: Linux) Remove Override For NGINX Systemd Service"
  file:
    path: "{{ nginx_service_overridepath }}"
    state: absent
  notify: "(Handler: All OSs) Systemd Daemon-Reload"
  when: nginx_service_clean
