---
- name: (FreeBSD) Update ports
  when:
    - ansible_facts['system'] == 'FreeBSD'
    - nginx_bsd_update_ports | bool
  block:
    - name: (FreeBSD) Fetch ports
      ansible.builtin.command:
        cmd: portsnap fetch --interactive
        creates: /var/db/portsnap/INDEX

    - name: (FreeBSD) Extract ports
      ansible.builtin.command:
        cmd: portsnap extract
        creates: /usr/ports

- name: (DragonFlyBSD/FreeBSD/HardenedBSD) {{ nginx_setup | capitalize }} NGINX
  when: ansible_facts['system'] in ['DragonFlyBSD', 'FreeBSD', 'HardenedBSD']
  block:
    - name: (DragonFlyBSD/FreeBSD/HardenedBSD) {{ nginx_setup | capitalize }} NGINX package
      community.general.pkgng:
        name: www/nginx{{ nginx_version | default('') }}
        state: "{{ nginx_state }}"
      when: nginx_bsd_install_packages | bool
      notify: (Handler) Run NGINX

    - name: (DragonFlyBSD/FreeBSD/HardenedBSD) {{ nginx_setup | capitalize }} NGINX port
      when: not nginx_bsd_install_packages | bool
      block:
        - name: (FreeBSD) {{ nginx_setup | capitalize }} NGINX port
          community.general.portinstall:
            name: www/nginx{{ nginx_version | default('') }}
            use_packages: "{{ nginx_bsd_portinstall_use_packages | default(omit) }}"
            state: "{{ nginx_state }}"
          when: ansible_facts['system'] == 'FreeBSD'
          notify: (Handler) Run NGINX

        - name: (DragonFlyBSD/HardenedBSD) {{ nginx_setup | capitalize }} NGINX port
          ansible.builtin.fail:
            msg: "{{ ansible_facts['system'] }} {{ nginx_setup | capitalize }} NGINX port not implemented."
          when: ansible_facts['system'] in ['DragonFlyBSD', 'HardenedBSD']

- name: (OpenBSD) {{ nginx_setup | capitalize }} NGINX
  when: ansible_facts['system'] == 'OpenBSD'
  block:
    - name: (OpenBSD) {{ nginx_setup | capitalize }} NGINX package
      community.general.openbsd_pkg:
        name: nginx{{ nginx_version | default('') }}
        build: false
        state: "{{ nginx_state }}"
      when: nginx_bsd_install_packages | bool
      notify: (Handler) Run NGINX

    - name: (OpenBSD) {{ nginx_setup | capitalize }} NGINX port
      community.general.openbsd_pkg:
        name: nginx{{ nginx_version | default('') }}
        build: true
        state: "{{ nginx_state }}"
      when: not nginx_bsd_install_packages | bool
      notify: (Handler) Run NGINX

- name: (NetBSD) {{ nginx_setup | capitalize }} NGINX
  when: ansible_facts['system'] == 'NetBSD'
  block:
    - name: (NetBSD) {{ nginx_setup | capitalize }} NGINX package
      community.general.pkgin:
        name: nginx{{ nginx_version | default('') }}
        state: "{{ (nginx_state == 'uninstall') | ternary('absent', 'present') }}"
      when: nginx_bsd_install_packages | bool
      notify: (Handler) Run NGINX

    - name: (NetBSD) {{ nginx_setup | capitalize }} NGINX port
      ansible.builtin.fail:
        msg: "{{ ansible_facts['system'] }} {{ nginx_setup | capitalize }} NGINX port not implemented."
      when: not nginx_bsd_install_packages | bool
