---
- name: "(Install: Debian/Ubuntu) Set Default APT NGINX Repository"
  set_fact:
    default_repository:
      - >-
        deb [arch=amd64] https://nginx.org/packages/{{ (nginx_branch == 'mainline')
        | ternary('mainline/', '') }}{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx
      - >-
        deb-src [arch=amd64] https://nginx.org/packages/{{ (nginx_branch == 'mainline')
        | ternary('mainline/', '') }}{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx

- name: "(Install: Debian/Ubuntu) Set APT NGINX Repository"
  set_fact:
    repository: "{{ nginx_repository | default(default_repository) }}"

- name: "(Install: Debian/Ubuntu) Add NGINX Repository"
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "{{ repository }}"

- name: "(Install: Debian/Ubuntu) Install NGINX"
  apt:
    name: "nginx{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
  notify: "(Handler: All OSs) Start NGINX"
