---
- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) {{ (nginx_license_status is defined or nginx_setup == 'uninstall') | ternary('Remove', 'Configure') }} NGINX Plus repository
  ansible.builtin.yum_repository:
    name: nginx-plus
    baseurl: "{{ nginx_repository | default(lookup('vars', 'nginx_plus_default_repository_' + ((ansible_facts['distribution'] == 'Amazon') | ternary('amazon', 'redhat')))) }}"
    description: NGINX Plus Repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_license_status | default((nginx_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0644
  when: nginx_manage_repo | bool

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Force Yum cache refresh
  ansible.builtin.command: yum clean metadata
  when: nginx_manage_repo | bool
  changed_when: false

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) {{ nginx_setup | capitalize }} NGINX Plus
  ansible.builtin.yum:
    name: nginx-plus{{ nginx_version | default('') }}
    state: "{{ nginx_state }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version.full is version('2.12', '<') else true }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler) Run NGINX
