---
- name: (SLES) {{ nginx_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  community.general.zypper_repository:
    name: nginx-plus
    repo: "{{ nginx_repository | default(nginx_plus_default_repository_suse) }}"
    state: "{{ nginx_license_status | default((nginx_setup == 'uninstall') | ternary('absent', 'present')) }}"
  when: nginx_manage_repo | bool

- name: (SLES) {{ nginx_setup | capitalize }} NGINX Plus
  community.general.zypper:
    name: nginx-plus{{ nginx_version | default('') }}
    state: "{{ nginx_state }}"
    update_cache: true
    oldpackage: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler) Run NGINX
