---
- name: (Alpine Linux) {{ nginx_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_repository | default(nginx_plus_default_repository_alpine) }}"
    state: "{{ nginx_license_status | default((nginx_setup == 'uninstall') | ternary('absent', 'present')) }}"
  when: nginx_manage_repo | bool

- name: (Alpine Linux) {{ nginx_setup | capitalize }} NGINX Plus
  community.general.apk:
    name: nginx-plus{{ nginx_version | default('') }}
    repository: "{{ nginx_repository | default(nginx_plus_default_repository_alpine) }}"
    state: "{{ nginx_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler) Run NGINX
