---
- name: "(Setup: Debian/Ubuntu) Setup NGINX Plus Repository"
  apt_repository:
    repo: deb [arch=amd64] https://plus-pkgs.nginx.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx-plus
    filename: nginx-plus
    update_cache: no
    state: "{{ nginx_license_status | default ('present') }}"

- name: "(Setup: Debian/Ubuntu) Setup NGINX Plus License"
  blockinfile:
    path: /etc/apt/apt.conf.d/90nginx
    create: yes
    block: |
      Acquire::https::plus-pkgs.nginx.com::Verify-Peer "true";
      Acquire::https::plus-pkgs.nginx.com::Verify-Host "true";
      Acquire::https::plus-pkgs.nginx.com::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::plus-pkgs.nginx.com::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nginx_license_status | default ('present') }}"

- name: "(Setup: Debian/Ubuntu) Update APT Cache"
  apt:
    update_cache: yes
